name = "custom-navigation-page"
account_id = "3fd5f0d412723c40fbbf9db0ea688ddb"
workers_dev = true
compatibility_date = "2025"
main = "worker.js"

# 将原内联表格式改为标准TOML表格格式
[env.NAV_SETTINGS]
binding = "NAV_SETTINGS"
type = "kv_namespace"
id = "YOUR_KV_NAMESPACE_ID"

